/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment;

import static org.junit.Assert.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class AppTest {
  @Test
  public void testApp_has_a_greeting() {
    App classUnderTest = new App();
    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  }

  private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
  private final PrintStream originalOut = System.out;

  @Before
  public void setUpStreams() {
    System.setOut(new PrintStream(outContent));
  }

  @After
  public void restoreStreams() {
    System.setOut(originalOut);
  }

  @Test
  public void out() {
    App.main(null);
    assertEquals("Hello world.\n", outContent.toString());
  }

  @Test
  public void challenge1(){
    App classUnderTest = new App();
    String answer = "a + b - 2 * c2 * x / (y * z)(x + 3) * (n % p)-a / -(b + c)x / y % -zx / (y % -z)";
    assertEquals(answer, classUnderTest.challenge1());
  }

  @Test
  public void challenge2(){
    App classUnderTest = new App();
    String answer = "value:30, type:intvalue:210, type:intvalue:200, type:intvalue:6100, type:longvalue:50002.5, " +
        "type:floatvalue:400.0, type:floatvalue:800.0, type:doublevalue:800.0, type:float";
    assertEquals(answer, classUnderTest.challenge2());
  }

  @Test
  public void challenge3(){
    App classUnderTest = new App();
    String answer = "21";
    assertEquals(answer, classUnderTest.challenge3());
  }

  @Test
  public void challenge4(){
    App classUnderTest = new App();
    String answer = "value:61, type:intvalue:120, type:intvalue:2, type:intvalue:600, type:int";
    assertEquals(answer, classUnderTest.challenge4());
  }

  @Test
  public void challenge5(){
    App classUnderTest = new App();
    String answer = "false 10 5false10 6true 10 7true 10 7";
    assertEquals(answer, classUnderTest.challenge5());
  }

  @Test
  public void challenge6(){
    App classUnderTest = new App();
    String answer = "falsetruefalsetruetruefalsefalsetrue";
    assertEquals(answer, classUnderTest.challenge6());
  }

  @Test
  public void challenge7(){
    App classUnderTest = new App();
    String answer = "i=1 n=0i=11 n=11i=21 j=6 n=120i=18 n=18i=12 j=4 n=12";
    assertEquals(answer, classUnderTest.challenge7());
  }
}
